version: '3.8'

services:
  frontend:
    env_file:
      - "frontend.env"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8080  # Changed from localhost to container name
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network  # Added network

  backend:
    env_file:
      - "backend.env"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GIN_MODE=debug
      - PORT=8080
    networks:
      - app-network  # Added network

networks:  # Define the network
  app-network:
    driver: bridge
